default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: movie_reviews_development
  host: localhost
  username: postgres
  password: 686969

test:
  <<: *default
  database: movie_reviews_test
  host: localhost
  username: postgres
  password: 686969

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  
  # 添加这个配置用于Action Cable
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>